### ISSUE TITLE
module is not defined

### ISSUE THREAD

**Issue by vinnygambiny** [SkipTheDragon/inertia-bundle#12]
When I just call the usePage(), I got this error. Someone know why ? 

`const props = usePage().props;`

```
ReferenceError: module is not defined
    at ./node_modules/@inertiajs/react/dist/index.js (index.js:1:694)
    at __webpack_require__ (bootstrap:19:1)
    at ./assets/Pages/demo.tsx (demo.tsx:7:17)
    at __webpack_require__ (bootstrap:19:1)
    at webpackContext (.*$:9:1)
    at resolve (app.js:17:22)
    at l (index.esm.js:5:1422)
    at V (index.esm.js:5:1422)
    at ./assets/app.js (app.js:16:17)
    at __webpack_require__ (bootstrap:19:1)
```

**Comment by vinnygambiny** [comment]
I have found !

I need `"module": "es2015",` in the tsconfig.json

It's work
